RecipeBox/Models/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;

namespace RecipeBox.Models
{
  public class ApplicationUser : IdentityUser
  {

  }
}

RecipeBox/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace RecipeBox.Models
{
  public class RecipeBoxContextFactory : IDesignTimeDbContextFactory<RecipeBoxContext>
  {

    RecipeBoxContext IDesignTimeDbContextFactory<RecipeBoxContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<RecipeBoxContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new RecipeBoxContext(builder.Options);
    }
  }
}

RecipeBox/Models/Recipe.cs
using System.Collections.Generic;

namespace RecipeBox.Models
{
  public class Recipe
  {
    public Recipe()
    {
      this.JoinEntities = new HashSet<RecipeTag>();
    }
    public int RecipeId { get; set; }
    public string Name { get; set; }
    public string Ingredients { get; set; }
    public string Instructions { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual ICollection<RecipeTag> JoinEntities { get; }
  }
}

RecipeBox/Models/RecipeBoxContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace RecipeBox.Models
{
  public class RecipeBoxContext : IdentityDbContext<ApplicationUser> 
  {
    public DbSet<Tag> Tags { get; set; }
    public DbSet<Recipe> Recipes { get; set; }
    public DbSet<RecipeTag> RecipeTag { get; set; }

    public RecipeBoxContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

RecipeBox/Models/RecipeTag.cs
namespace RecipeBox.Models
{
  public class RecipeTag
  {
    public int RecipeTagId { get; set; }
    public int RecipeId { get; set; }
    public int TagId { get; set; }
    public virtual Recipe Recipe { get; set; }
    public virtual Tag Tag { get; set; }
  }

}

RecipeBox/Models/Tag.cs
using System.Collections.Generic;

namespace RecipeBox.Models
{
  public class Tag 
  {
    public Tag()
    {
      this.JoinEntities = new HashSet<RecipeTag>();
    }
    public int TagId { get; set; }
    public string Name { get; set; }
    public virtual ICollection<RecipeTag> JoinEntities { get; set; }

  }
}

RecipeBox/ViewModels/LoginViewModel.cs
namespace RecipeBox.ViewModels
{
    public class LoginViewModel
    {
        public string Email { get; set; }
        public string Password { get; set; }
    }
}

RecipeBox/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace RecipeBox.ViewModels
{
  public class RegisterViewModel
  {
    [Required]
    [EmailAddress]
    [Display(Name = "Email")]
    public string Email { get; set; }

    [Required]
    [DataType(DataType.Password)]
    [Display(Name = "Password")]
    public string Password { get; set; }

    [DataType(DataType.Password)]
    [Display(Name = "Confirm Password")]
    [Compare("Password", ErrorMessage = "The inputted passwords do not match.")]
    public string ConfirmPassword { get; set; }
  }
}

RecipeBox/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using RecipeBox.Models;
using System.Threading.Tasks;
using RecipeBox.ViewModels;

namespace RecipeBox.Controllers
{
  public class AccountController : Controller
  {
    private readonly RecipeBoxContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly SignInManager<ApplicationUser> _signInManager;

    public AccountController(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager, RecipeBoxContext db)
    {
      _userManager = userManager;
      _signInManager = signInManager;
      _db = db;
    }

    public ActionResult Index()
    {
      return View();
    }
    public IActionResult Register()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Register (RegisterViewModel model)
    {
      var user = new ApplicationUser { UserName = model.Email };
      IdentityResult result = await _userManager.CreateAsync(user, model.Password);
      if (result.Succeeded)
      {
        return RedirectToAction("Index");
      }
      else
      {
        return View();
      } 
    }

    public ActionResult Login()
    {
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Login(LoginViewModel model)
    {
      Microsoft.AspNetCore.Identity.SignInResult result = await _signInManager.PasswordSignInAsync(model.Email, model.Password, isPersistent: true, lockoutOnFailure: false);
      if (result.Succeeded)
      {
        return RedirectToAction("Index");
      }
      else
      {
        return View();
      }
    }
    [HttpPost]
    public async Task<ActionResult> LogOff()
    {
      await _signInManager.SignOutAsync();
      return RedirectToAction("Index");
    }
  }
}

RecipeBox/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace RecipeBox.Controllers
{
  public class HomeController : Controller
  {
    [HttpGet("/")]
    public ActionResult Index()
    {
      return View();
    }
  }
}

RecipeBox/Controllers/RecipesController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;

namespace RecipeBox.Controllers
{
  [Authorize]
  public class RecipesController : Controller
  {
    private readonly RecipeBoxContext _db;
    private readonly UserManager<ApplicationUser> _userManager;
    public RecipesController(UserManager<ApplicationUser> userManager, RecipeBoxContext db)
    {
      _userManager = userManager;
      _db = db;
    }
    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      var userItems = _db.Recipes.Where(entry => entry.User.Id == currentUser.Id).ToList();
      // var userItems = _db.Recipes.ToList();
      return View(userItems);
    }

    public ActionResult Create()
    {
      //Get your tags into your recipe create page route
      ViewBag.TagId = new SelectList(_db.Tags, "TagId", "Name");
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Recipe recipe, int TagId)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);//gets who's signed in
      recipe.User = currentUser;//sets userId to who's signed in
      _db.Recipes.Add(recipe); //adds all that to db
      _db.SaveChanges();
       if (TagId != 0)
      {
          _db.RecipeTag.Add(new RecipeTag() { TagId = TagId, RecipeId = recipe.RecipeId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisRecipe = _db.Recipes
      .Include(recipe => recipe.JoinEntities)
      .ThenInclude(join => join.Tag)
      .FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(thisRecipe);
    }
  }
}

RecipeBox/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using RecipeBox.Models;
using System.Collections.Generic;
using System.Linq;

namespace RecipeBox.Controllers
{
  public class TagsController : Controller
  {
    private readonly RecipeBoxContext _db;

    public TagsController(RecipeBoxContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Tags.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Tag tag)
    {
      _db.Tags.Add(tag);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      var thisTag = _db.Tags
      .Include(tag => tag.JoinEntities)
      .ThenInclude(join => join.Recipe)
      .FirstOrDefault(tag => tag.TagId == id);
      return View(thisTag);
    }
  }
}

RecipeBox/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to RecipeBox - a website to hold your recipes!</h1>

RecipeBox/Views/Recipes/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Recipe

<h2>Add a new recipe</h2>
  <div class="main">
    @using (Html.BeginForm())
    {
      @Html.LabelFor(m => m.Name)
      @Html.TextBoxFor(m => m.Name, new { @required="true"})

      @Html.LabelFor(m => m.Ingredients)
      @Html.TextAreaFor(m => m.Ingredients, new { @required="true"})

      @Html.LabelFor(m => m.Instructions)
      @Html.TextAreaFor(m => m.Instructions, new {@required="true"})

      @Html.Label("Select tag: ")
      @Html.DropDownList("TagId", string.Empty)


      <input type="submit" value="Add new recipe" class="btn btn-submit" />
    }
</div>

RecipeBox/Views/Recipes/Details.cshtml
@{
  Layout = "_Layout";
}
@model RecipeBox.Models.Recipe

<h2>Recipe Details</h2>

<div class="main">
  <h3>@Html.DisplayNameFor(m => m.Name): @Html.DisplayFor(m => m.Name)</h3>
  <h3>@Html.DisplayNameFor(m => m.Ingredients): @Html.DisplayFor(m => m.Ingredients)</h3>
  <h3>@Html.DisplayNameFor(m => m.Instructions): @Html.DisplayFor(m => m.Instructions)</h3>

  @if(@Model.JoinEntities.Count == 0)
  {
    <p>This recipe does not belong to any tags</p>
  }
  else
  {
    <h4>Tags this recipe has:</h4>
    <ul>
      @foreach(var join in Model.JoinEntities)
      {
        <li><h3>@join.Tag.Name</h3></li>
        @using (Html.BeginForm("DeleteTag", "Recipes"))
        {
          @Html.Hidden("joinId", @join.RecipeTagId)
          <input type = "submit" value = "Delete Tag" class="btn btn-submit" />
        }
      }
    </ul>
  }
</div>

RecipeBox/Views/Recipes/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models;
@model List<RecipeBox.Models.Recipe>

  <h1>Recipes for @User.Identity.Name</h1>
  <div class="main">
    @if (Model.Any()) 
    {
      <div class="main">
        <ul>
          @foreach (Recipe recipe in Model)
          {
            <li>@Html.ActionLink($"{recipe.Name}", "Details", new { id = recipe.RecipeId })</li>
          }
        </ul>
      </div>
    }
    else 
    {  
      <h3>No recipes have been added as of yet</h3>  
       @Html.ActionLink("Add new recipe", "Create", "Recipes")
    }
  </div>

  

RecipeBox/Views/Shared/Menu.cshtml
<ul class="menu">
  <li>@Html.ActionLink("Home", "Index", "Home")</li>
  <li>@Html.ActionLink("See all recipes", "Index", "Recipes")</li>
  <li>@Html.ActionLink("See all tags", "Index", "Tags")</li>
  <li>@Html.ActionLink("Add new recipe", "Create", "Recipes")</li>
  <li>@Html.ActionLink("Add new tag", "Create", "Tags")</li>
  <li>@Html.ActionLink("Create an Account", "Index", "Account")</li>
  <li>@Html.ActionLink("Log in", "Login", "Account")</li>  
  <li> @using (Html.BeginForm("LogOff", "Account"))
    {
      <input type="submit" value="Log out" />
    }</li> 
</ul>

RecipeBox/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>RecipeRecipeRecipe</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    <div class="container">
    @RenderBody()
    @await Html.PartialAsync("Menu")
    </div>
  </body>
</html>

RecipeBox/Views/Tags/Create.cshtml
@{
  Layout = "_Layout";
}

@model RecipeBox.Models.Tag

<h2>Add a new tag</h2>
<div class="main">
  @using (Html.BeginForm())
  {
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)
    <input type="submit" value="Add a new tag" class="btn btn-submit">
  }
</div>

RecipeBox/Views/Tags/Details.cshtml
@{
  Layout = "_Layout";
}
@model RecipeBox.Models.Tag;

<h2>Tag Details</h2>
<div class="main">
  <h3>@Html.DisplayNameFor(m => m.Name): @Html.DisplayFor(m => m.Name)</h3>

  @if(@Model.JoinEntities.Count == 0)
  {
    <p>This tag does not include any recipes</p>
  }
  else 
  {
    <h4>Recipe this tag contains</h4>
    <ul>
      @foreach(var join in Model.JoinEntities)
      {
        <li>@Html.ActionLink($"{join.Recipe.Name}", "Details", "Recipes", new { id = join.Recipe.RecipeId})</li>
      }
    </ul>
  }



</div>

RecipeBox/Views/Tags/Index.cshtml
@{
  Layout = "_Layout";
}

@using RecipeBox.Models;

<h1>Tags</h1>
<div class="main">
  @if (Model.Count == 0)
  {
    <h3>No tags have been added yet.</h3>
    @Html.ActionLink("Add new tag", "Create", "Tags")
  }

  <ul>
    @foreach(Tag tag in Model)
    {
      <li>@Html.ActionLink($"{tag.Name}", "Details", new { id = tag.TagId})</li>
    }
  </ul>
</div>